<?php
/**
 * Created by PhpStorm.
 * User: lukas
 * Date: 22/03/19
 * Time: 11:34
 */

?>

<!doctype html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport"
          content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>Document</title>
</head>
<body>
<h1>Hello, let's work</h1>
</body>
</html>

